/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_DASH_DASH_DASH_DASH = 2,
  sym__name = 3,
  anon_sym_EQ = 4,
  sym_command = 5,
  sym_before = 6,
  sym_after = 7,
  anon_sym_PIPE = 8,
  sym_comment = 9,
  sym_source_file = 10,
  sym_shelf = 11,
  sym_node_name = 12,
  sym_before_name = 13,
  sym_after_name = 14,
  sym__node = 15,
  sym_before_nodes = 16,
  sym_after_nodes = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym__node_repeat1 = 19,
  aux_sym_before_nodes_repeat1 = 20,
  aux_sym_after_nodes_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_DASH_DASH_DASH_DASH] = "----",
  [sym__name] = "_name",
  [anon_sym_EQ] = "=",
  [sym_command] = "command",
  [sym_before] = "before",
  [sym_after] = "after",
  [anon_sym_PIPE] = "|",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_shelf] = "shelf",
  [sym_node_name] = "node_name",
  [sym_before_name] = "before_name",
  [sym_after_name] = "after_name",
  [sym__node] = "_node",
  [sym_before_nodes] = "before_nodes",
  [sym_after_nodes] = "after_nodes",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__node_repeat1] = "_node_repeat1",
  [aux_sym_before_nodes_repeat1] = "before_nodes_repeat1",
  [aux_sym_after_nodes_repeat1] = "after_nodes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_DASH_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH_DASH,
  [sym__name] = sym__name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_command] = sym_command,
  [sym_before] = sym_before,
  [sym_after] = sym_after,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_shelf] = sym_shelf,
  [sym_node_name] = sym_node_name,
  [sym_before_name] = sym_before_name,
  [sym_after_name] = sym_after_name,
  [sym__node] = sym__node,
  [sym_before_nodes] = sym_before_nodes,
  [sym_after_nodes] = sym_after_nodes,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__node_repeat1] = aux_sym__node_repeat1,
  [aux_sym_before_nodes_repeat1] = aux_sym_before_nodes_repeat1,
  [aux_sym_after_nodes_repeat1] = aux_sym_after_nodes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_before] = {
    .visible = true,
    .named = true,
  },
  [sym_after] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_shelf] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_before_name] = {
    .visible = true,
    .named = true,
  },
  [sym_after_name] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_before_nodes] = {
    .visible = true,
    .named = true,
  },
  [sym_after_nodes] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_before_nodes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_after_nodes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == '|') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(18);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_command);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_before);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_after);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(1),
    [sym__name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_before] = ACTIONS(1),
    [sym_after] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym_shelf] = STATE(2),
    [sym_node_name] = STATE(4),
    [sym__node] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(9),
    [sym__name] = ACTIONS(11),
    [sym_comment] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_DASH_DASH_DASH_DASH,
    ACTIONS(11), 1,
      sym__name,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_node_name,
    ACTIONS(15), 2,
      aux_sym_source_file_token1,
      sym_comment,
    STATE(3), 3,
      sym_shelf,
      sym__node,
      aux_sym_source_file_repeat1,
  [22] = 6,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(22), 1,
      anon_sym_DASH_DASH_DASH_DASH,
    ACTIONS(25), 1,
      sym__name,
    STATE(4), 1,
      sym_node_name,
    ACTIONS(19), 2,
      aux_sym_source_file_token1,
      sym_comment,
    STATE(3), 3,
      sym_shelf,
      sym__node,
      aux_sym_source_file_repeat1,
  [44] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(28), 1,
      aux_sym_source_file_token1,
    ACTIONS(30), 1,
      anon_sym_EQ,
    ACTIONS(32), 1,
      sym_before,
    ACTIONS(34), 1,
      sym_after,
    STATE(5), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [65] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_before,
    ACTIONS(34), 1,
      sym_after,
    ACTIONS(36), 1,
      aux_sym_source_file_token1,
    ACTIONS(38), 1,
      anon_sym_EQ,
    STATE(6), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [86] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      sym_before,
    ACTIONS(45), 1,
      sym_after,
    ACTIONS(40), 2,
      aux_sym_source_file_token1,
      anon_sym_EQ,
    STATE(6), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [105] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_PIPE,
    STATE(9), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(48), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [121] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(52), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_PIPE,
    STATE(11), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(56), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [153] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(58), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [169] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_PIPE,
    STATE(11), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(60), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(65), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [234] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [245] = 1,
    ACTIONS(74), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
      sym_comment,
  [253] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [263] = 1,
    ACTIONS(78), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
      sym_comment,
  [271] = 1,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
      sym_comment,
  [279] = 1,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
      sym_comment,
  [287] = 1,
    ACTIONS(84), 5,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
      sym_comment,
  [295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__name,
    STATE(8), 1,
      sym_after_name,
  [305] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__name,
    STATE(7), 1,
      sym_before_name,
  [315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__name,
    STATE(16), 1,
      sym_before_name,
  [325] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__name,
    STATE(15), 1,
      sym_after_name,
  [335] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      aux_sym_source_file_token1,
  [342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_source_file_token1,
  [349] = 2,
    ACTIONS(94), 1,
      sym_command,
    ACTIONS(96), 1,
      sym_comment,
  [356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [363] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      aux_sym_source_file_token1,
  [370] = 2,
    ACTIONS(96), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym_command,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 86,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 121,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 153,
  [SMALL_STATE(11)] = 169,
  [SMALL_STATE(12)] = 185,
  [SMALL_STATE(13)] = 201,
  [SMALL_STATE(14)] = 212,
  [SMALL_STATE(15)] = 223,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 245,
  [SMALL_STATE(18)] = 253,
  [SMALL_STATE(19)] = 263,
  [SMALL_STATE(20)] = 271,
  [SMALL_STATE(21)] = 279,
  [SMALL_STATE(22)] = 287,
  [SMALL_STATE(23)] = 295,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 315,
  [SMALL_STATE(26)] = 325,
  [SMALL_STATE(27)] = 335,
  [SMALL_STATE(28)] = 342,
  [SMALL_STATE(29)] = 349,
  [SMALL_STATE(30)] = 356,
  [SMALL_STATE(31)] = 363,
  [SMALL_STATE(32)] = 370,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_nodes, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_nodes, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_nodes, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_nodes, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_before_nodes_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_before_nodes_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_after_nodes_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_after_nodes_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_name, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_name, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shelf, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 4, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [98] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_deml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
