/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_DASH_DASH_DASH_DASH = 2,
  sym__name = 3,
  anon_sym_EQ = 4,
  sym_command = 5,
  sym_before = 6,
  sym_after = 7,
  anon_sym_PIPE = 8,
  sym_comment = 9,
  sym_source_file = 10,
  sym_shelf = 11,
  sym_node_name = 12,
  sym_before_name = 13,
  sym_after_name = 14,
  sym__node = 15,
  sym_before_nodes = 16,
  sym_after_nodes = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_source_file_repeat2 = 19,
  aux_sym__node_repeat1 = 20,
  aux_sym_before_nodes_repeat1 = 21,
  aux_sym_after_nodes_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_DASH_DASH_DASH_DASH] = "----",
  [sym__name] = "_name",
  [anon_sym_EQ] = "=",
  [sym_command] = "command",
  [sym_before] = "before",
  [sym_after] = "after",
  [anon_sym_PIPE] = "|",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_shelf] = "shelf",
  [sym_node_name] = "node_name",
  [sym_before_name] = "before_name",
  [sym_after_name] = "after_name",
  [sym__node] = "_node",
  [sym_before_nodes] = "before_nodes",
  [sym_after_nodes] = "after_nodes",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym__node_repeat1] = "_node_repeat1",
  [aux_sym_before_nodes_repeat1] = "before_nodes_repeat1",
  [aux_sym_after_nodes_repeat1] = "after_nodes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_DASH_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH_DASH,
  [sym__name] = sym__name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_command] = sym_command,
  [sym_before] = sym_before,
  [sym_after] = sym_after,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_shelf] = sym_shelf,
  [sym_node_name] = sym_node_name,
  [sym_before_name] = sym_before_name,
  [sym_after_name] = sym_after_name,
  [sym__node] = sym__node,
  [sym_before_nodes] = sym_before_nodes,
  [sym_after_nodes] = sym_after_nodes,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym__node_repeat1] = aux_sym__node_repeat1,
  [aux_sym_before_nodes_repeat1] = aux_sym_before_nodes_repeat1,
  [aux_sym_after_nodes_repeat1] = aux_sym_after_nodes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_before] = {
    .visible = true,
    .named = true,
  },
  [sym_after] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_shelf] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_before_name] = {
    .visible = true,
    .named = true,
  },
  [sym_after_name] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_before_nodes] = {
    .visible = true,
    .named = true,
  },
  [sym_after_nodes] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__node_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_before_nodes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_after_nodes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead == '|') ADVANCE(20);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(4);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(4);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_command);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_before);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_after);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(1),
    [sym__name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_before] = ACTIONS(1),
    [sym_after] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(34),
    [sym_node_name] = STATE(3),
    [sym__node] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym__name] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__name,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      aux_sym_source_file_token1,
    ACTIONS(11), 1,
      anon_sym_DASH_DASH_DASH_DASH,
    STATE(3), 1,
      sym_node_name,
    STATE(15), 1,
      aux_sym_source_file_repeat2,
    STATE(22), 1,
      sym_shelf,
    STATE(5), 2,
      sym__node,
      aux_sym_source_file_repeat1,
  [29] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      aux_sym_source_file_token1,
    ACTIONS(15), 1,
      anon_sym_EQ,
    ACTIONS(17), 1,
      sym_before,
    ACTIONS(19), 1,
      sym_after,
    STATE(4), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [50] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_before,
    ACTIONS(19), 1,
      sym_after,
    ACTIONS(21), 1,
      aux_sym_source_file_token1,
    ACTIONS(23), 1,
      anon_sym_EQ,
    STATE(7), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [71] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym__name,
    STATE(3), 1,
      sym_node_name,
    STATE(5), 2,
      sym__node,
      aux_sym_source_file_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
  [90] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__name,
    STATE(3), 1,
      sym_node_name,
    STATE(5), 2,
      sym__node,
      aux_sym_source_file_repeat1,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
  [109] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(34), 1,
      sym_before,
    ACTIONS(37), 1,
      sym_after,
    ACTIONS(32), 2,
      aux_sym_source_file_token1,
      anon_sym_EQ,
    STATE(7), 3,
      sym_before_nodes,
      sym_after_nodes,
      aux_sym__node_repeat1,
  [128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(11), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(40), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [144] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(44), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(48), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [176] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(50), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [192] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_PIPE,
    STATE(12), 1,
      aux_sym_before_nodes_repeat1,
    ACTIONS(52), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      aux_sym_after_nodes_repeat1,
    ACTIONS(57), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [224] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [235] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_DASH_DASH_DASH_DASH,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      aux_sym_source_file_token1,
    STATE(18), 1,
      aux_sym_source_file_repeat2,
    STATE(22), 1,
      sym_shelf,
  [254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [265] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [276] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_DASH_DASH_DASH_DASH,
    STATE(18), 1,
      aux_sym_source_file_repeat2,
    STATE(22), 1,
      sym_shelf,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
  [293] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 5,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
      anon_sym_PIPE,
  [304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
  [324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__name,
    STATE(3), 1,
      sym_node_name,
    STATE(6), 2,
      sym__node,
      aux_sym_source_file_repeat1,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
  [348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 4,
      aux_sym_source_file_token1,
      anon_sym_EQ,
      sym_before,
      sym_after,
  [358] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_DASH_DASH_DASH_DASH,
      sym__name,
  [368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym__name,
    STATE(17), 1,
      sym_before_name,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym__name,
    STATE(9), 1,
      sym_after_name,
  [388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      sym__name,
    STATE(8), 1,
      sym_before_name,
  [398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym__name,
    STATE(19), 1,
      sym_after_name,
  [408] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym__name,
  [415] = 2,
    ACTIONS(89), 1,
      sym_command,
    ACTIONS(91), 1,
      sym_comment,
  [422] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
  [429] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [436] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
  [443] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_source_file_token1,
  [450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      aux_sym_source_file_token1,
  [457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      aux_sym_source_file_token1,
  [464] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_command,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 71,
  [SMALL_STATE(6)] = 90,
  [SMALL_STATE(7)] = 109,
  [SMALL_STATE(8)] = 128,
  [SMALL_STATE(9)] = 144,
  [SMALL_STATE(10)] = 160,
  [SMALL_STATE(11)] = 176,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 208,
  [SMALL_STATE(14)] = 224,
  [SMALL_STATE(15)] = 235,
  [SMALL_STATE(16)] = 254,
  [SMALL_STATE(17)] = 265,
  [SMALL_STATE(18)] = 276,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 304,
  [SMALL_STATE(21)] = 314,
  [SMALL_STATE(22)] = 324,
  [SMALL_STATE(23)] = 338,
  [SMALL_STATE(24)] = 348,
  [SMALL_STATE(25)] = 358,
  [SMALL_STATE(26)] = 368,
  [SMALL_STATE(27)] = 378,
  [SMALL_STATE(28)] = 388,
  [SMALL_STATE(29)] = 398,
  [SMALL_STATE(30)] = 408,
  [SMALL_STATE(31)] = 415,
  [SMALL_STATE(32)] = 422,
  [SMALL_STATE(33)] = 429,
  [SMALL_STATE(34)] = 436,
  [SMALL_STATE(35)] = 443,
  [SMALL_STATE(36)] = 450,
  [SMALL_STATE(37)] = 457,
  [SMALL_STATE(38)] = 464,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__node_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_nodes, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_nodes, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_nodes, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_nodes, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_before_nodes_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_before_nodes_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_after_nodes_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_after_nodes_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_before_name, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_after_name, 1, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(35),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__node, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shelf, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_deml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
